### ISSUE TITLE
Can I generate .so files instead of static binaries using same script?

### ISSUE THREAD

**Issue by sagartrehan** [floriandejonckheere/rsync-android#2]
Sorry for asking irrelevant or dumb question.

The build script that you have provided is generating the static binaries(Does not has .so extension).

I wanted to write JNI wrapper on Rsync instead of directly running commands Runtime.getRuntime().exec().

Does the files generated by your script are shared object files only?

**Comment by floriandejonckheere** [comment]
The script uses the rsync source code to build a static binary. Unfortunately, I have no idea if it is possible to build a shared library from it, you should probably search through the rsync source code and documentation to find out how to do this. Good luck!
